plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ritsard'
version = '0.0.1-SNAPSHOT'
description = 'Practice project for future'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}


def repoUsername = System.getenv("NEXUS_USERNAME") ?: findProperty("nexus.username") ?: "guest"
def repoPassword = System.getenv("NEXUS_PASSWORD") ?: findProperty("nexus.password") ?: "!Guest@8081"
def repoReleaseUrl = "https://nexus.lodong.co.kr/repository/maven-releases/"
def repoSnapshotUrl = "https://nexus.lodong.co.kr/repository/maven-snapshots/"

repositories {
    mavenCentral()

    maven {
        name = "LodongReleases"
        url = uri(repoReleaseUrl)
        allowInsecureProtocol = true
        credentials {
            username = repoUsername
            password = repoPassword
        }
        content {
            includeGroup "com.lodong"
        }
        metadataSources {
            mavenPom()
            artifact()
        }
        authentication {
            basic(BasicAuthentication)
        }
    }

    maven {
        name = "LodongSnapshots"
        url = uri(repoSnapshotUrl)
        allowInsecureProtocol = true
        credentials {
            username = repoUsername
            password = repoPassword
        }
        content {
            includeGroup "com.lodong"
        }
        metadataSources {
            mavenPom()
            artifact()
        }
        authentication {
            basic(BasicAuthentication)
        }
    }
}

ext {
    set('springCloudVersion', "2023.0.1")
    set('lodongJwtMemberModule2Version', "0.1.88")
    set('lodongBaseModuleVersion', "0.1.8")
    set('lodongUtilsModuleVersion', "4.1.25")
    set('lodongFileModuleVersion', "0.1.55")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
    dependencies {
        dependency "com.lodong:jwt-member-module2:${lodongJwtMemberModule2Version}"
        dependency "com.lodong:base-module:${lodongBaseModuleVersion}"
        dependency "com.lodong:utils-module:${lodongUtilsModuleVersion}"
        dependency "com.lodong:file-module:${lodongFileModuleVersion}"
    }
}

dependencies {

    /* --- Core --- */
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'


    /* --- Database --- */
    runtimeOnly 'org.postgresql:postgresql'

    /* --- Swagger (Boot 4 compatible) --- */
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0'

    /* --- Lombok --- */
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    /* --- Dev --- */
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    /* --- Testing --- */
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'

    implementation 'commons-codec:commons-codec:1.20.0'
    implementation 'commons-io:commons-io:2.11.0'
    implementation 'org.jsoup:jsoup:1.16.1'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.2'
    implementation 'org.apache.commons:commons-lang3:3.13.0'

    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor 'com.querydsl:querydsl-apt:5.0.0:jakarta'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'

    implementation 'com.nimbusds:nimbus-jose-jwt:10.6'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.json:json:20230227'
    implementation 'org.hibernate.validator:hibernate-validator:7.0.2.Final'

//    Redis
    implementation 'org.springframework.data:spring-data-redis:3.2.1'

//    implementation "com.lodong:jwt-member-module2:${lodongJwtMemberModule2Version}"
//    implementation "com.lodong:base-module:${lodongBaseModuleVersion}"
//    implementation "com.lodong:utils-module:${lodongUtilsModuleVersion}"
//    implementation "com.lodong:file-module:${lodongFileModuleVersion}"
}

def querydslDir = "$buildDir/generated/querydsl"

sourceSets {
    main.java.srcDir querydslDir
}

clean {
    delete file(querydslDir)
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.generatedSourceOutputDirectory = file(querydslDir)
    options.compilerArgs += ['-parameters']
}

tasks.named('test') {
    useJUnitPlatform()
}

jar {
    enabled = false
}

bootJar {
    enabled = true
}

bootRun {
    jvmArgs = [
            '-Dspring.profiles.active=' + (findProperty('profile') ?: 'local'),
            '-Dfile.encoding=UTF-8',
            '-Duser.timezone=Asia/Seoul'
    ]
}
