version: "3.9"

services:
  baisard-api:
    image: baisard-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baisard-api
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 200303

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""

      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - shared-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 200303
    ports:
      - "5432:5432"
    volumes:
      - baisard_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
    networks:
      - shared-network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shared-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 200303
    ports:
      - "5050:80"
    networks:
      - shared-network

volumes:
  baisard_data:

networks:
  shared-network:
    driver: bridge
