services:
  baisard-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: baisard-api:latest
    container_name: baisard-api
    ports:
      - "1234:1234"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 200303
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AES_SECRET_KEY: wotkdvu@fcz1246GsJwlddutn_dlswndtlrtkgud

  frontend:
    build:
      context: ../baisard-ui   # This path relative to docker-compose.yml
      dockerfile: Dockerfile
    image: baisard-ui:latest
    container_name: baisard-ui
    ports:
      - "3000:3000"
    depends_on:
      - baisard-api
    environment:
      NEXT_PUBLIC_API_URL: http://baisard-api:1234

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 200303
    ports:
      - "5432:5432"
    volumes:
      - baisard_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 200303
    ports:
      - "5050:80"

volumes:
  baisard_data:
