# ============================================================================
# DEV Environment
# ============================================================================
server.port=1234

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=false

# File upload
app.upload.base-directory=/app
app.upload.max-file-size=30MB
app.upload.max-request-size=60MB

# Cookies
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.domain=ebook.com

# Redis
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}
spring.data.redis.timeout=2000ms
spring.data.redis.jedis.pool.max-active=20
spring.data.redis.jedis.pool.max-idle=10
spring.data.redis.jedis.pool.min-idle=5
spring.data.redis.jedis.pool.max-wait=-1ms
