# ============================================================================
# Datasource (PostgreSQL)
# ============================================================================
spring.datasource.driver-class-name=org.postgresql.Driver
# application-secret.properties
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.hfumhkxouoetstfvcbyc&password=wJcghhut4N1AEcEP
#spring.datasource.password=wJcghhut4N1AEcEP
#spring.datasource.url=jdbc:postgresql://localhost:5432/gpili
#spring.datasource.username=postgres
#spring.datasource.password=200303